Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,19 +11,19 @@ on:
           - info
           - warning
           - debug
-  push:
-    branches:
-      - main
-      - develop
-      - '[0-9]+.[0-9]+.[0-9]+-rc'
-    tags:
-      - '[0-9]+.[0-9]+.[0-9]+'
-  pull_request:
-    types: [opened, reopened, synchronize]
-    branches:
-      - main
-      - develop
-      - '[0-9]+.[0-9]+.[0-9]+-rc'
+  # push:
+  #   branches:
+  #     - main
+  #     - develop
+  #     - '[0-9]+.[0-9]+.[0-9]+-rc'
+  #   tags:
+  #     - '[0-9]+.[0-9]+.[0-9]+'
+  # pull_request:
+  #   types: [opened, reopened, synchronize]
+  #   branches:
+  #     - main
+  #     - develop
+  #     - '[0-9]+.[0-9]+.[0-9]+-rc'
 
 concurrency:
   group: ${{ github.ref }}
@@ -64,246 +64,246 @@ jobs:
       - name: Run Unit Tests
         run: ./build_unit_tests.sh --no-build --test
 
-      - name: Build cltool
-        run: ./build_cltool.sh
+      # - name: Build cltool
+      #   run: ./build_cltool.sh
 
-      - name: Build LogInspector
-        run: |
-          ./install_log_inspector_dependencies.sh
-          ./build_log_inspector.sh
-
-      - name: Build SDK Examples
-        run: python3 build_manager.py SDK_Examples ../ExampleProjects
-
-  ba_windows:
-    name: "General Software Windows"
-    runs-on: [self-hosted, windows, x64]
-    # if: false  # disable this job
-    # if: (github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/develop')   # Only run job on these branches
-
-    defaults:
-      run:
-        working-directory: scripts/windows
-
-    steps:
-      - name: Git checkout
-        uses: actions/checkout@v4
-        with:
-          # token: ${{ secrets.ALL_REPO_PAT }}
-          submodules: recursive
-          fetch-depth: 0  # Fetches full commit history, needed for repo info steps in build
-
-      - name: Install dependencies
-        run: ./install_sdk_dependencies.bat
-
-      - name: Clean all
-        run: ./clean_all.bat
-
-      - name: Build IS SDK library
-        run: ./build_is_sdk.bat
-
-      - name: Build Unit Tests
-        run: ./build_unit_tests.bat
-
-      - name: Run Unit Tests
-        run: ./build_unit_tests.bat --no-build --test
-        
-      - name: Build CLTool
-        run: ./build_cltool.bat
-
-      - name: Build LogInspector
-        run: ./build_log_inspector.bat
-
-      - name: Build SDK Examples
-        run: ./build_sdk_examples.bat
-
-  ros1-bridge-tests:
-    name: "ROS1 Bridge Tests"
-    runs-on: [self-hosted, Linux, X64, docker, focal]
-    timeout-minutes: 5
-    if: false  # disable this job -- ROS1 has been EOL'd and will be phased out.  We can no longer support it.
-
-    env:
-      ROS_CI_DESKTOP: "`lsb_release -cs`"  # e.g. [trusty|xenial|...]
-      ROS_DISTRO: noetic
-
-    container:
-      image: ros:noetic
-      #options: --privileged -v /dev:/dev
-      options: --device-cgroup-rule="c 166:* rmw"
-      volumes:
-        - "/dev:/dev"
-
-    defaults:
-      run:
-        working-directory: ../ROS/catkin_ws
-        shell: bash
-
-    steps:
-      - name: Update Git & CMake versions
-        working-directory: .
-        run: |
-          echo "::group::Install software-properties-common and dependencies."
-          apt-get update && apt -y install software-properties-common dirmngr apt-transport-https lsb-release ca-certificates libyaml-cpp-dev gpg wget curl
-          echo "::endgroup::"
-          echo "::group::Configure git-core PPA and install latest."
-          add-apt-repository ppa:git-core/ppa -y && apt -y install git
-          echo "::endgroup::"
-          git --version
-          echo "::group::Configure Kitware CMake PPA and install latest."
-          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
-          echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ `lsb_release -sc` main" | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
-          apt-get update
-          test -f /usr/share/doc/kitware-archive-keyring/copyright ||
-          rm /usr/share/keyrings/kitware-archive-keyring.gpg  
-          apt-get -y install kitware-archive-keyring cmake
-          echo "::endgroup::"
-          cmake --version
-
-      - name: Checkout source and submodules
-        uses: actions/checkout@v4
-        with:
-          # token: ${{ secrets.ALL_REPO_PAT }}
-          fetch-depth: 0  # Fetches full commit history, needed for repo info steps in build
-          submodules: recursive
-
-      - name: Install dependencies
-        working-directory: scripts
-        run: |
-          apt-get update && apt-get -y install python3-pip python3-venv python3-git python3-semver
-          ./install_sdk_dependencies.sh
-          ./install_python_dependencies.sh
-          ./install_gtest.sh
-
-      - name: Setup ROS environment
-        run: |
-          source /opt/ros/$ROS_DISTRO/setup.bash
-          echo "::group::Install ROS packages."
-          apt -y install ros-${ROS_DISTRO}-tf libusb-1.0-0-dev
-          echo "::endgroup::"
-          git config --global --add safe.directory /__w/inertial-sense-sdk/inertial-sense-sdk
-
-      - name: Setup Catkin Workspace and Build
-        run: |
-          source /opt/ros/$ROS_DISTRO/setup.bash
-          catkin_make -DCATKIN_BLACKLIST_PACKAGES="inertial_sense_ros2"
-          catkin_make test_unit_tests
-          catkin_make test_ros_bridge 
-
-      - name: Run Unit Tests
-        run: |          
-          source devel/setup.bash
-          rm -rf build/test_results
-          roscore &
-          catkin_make run_tests_inertial_sense_ros_gtest_test_unit_tests
-          catkin_test_results
-          pkill roscore
-
-      - name: Run Functional/Integration Tests (via hardware)
-        run: |
-          source devel/setup.bash
-          roscore &
-          catkin_make run_tests_inertial_sense_ros_gtest_test_ros_bridge
-          catkin_test_results
-
-      - name: Cleanup build folder to prevent future errors (Remove maybe?)
-        run: |
-          rm -rf ./* || true
-          rm -rf ./.??* || true
-
-  ros2-bridge-tests:
-    name: "ROS2 Bridge Tests"
-    runs-on: [self-hosted, Linux, X64, docker, focal]
-    timeout-minutes: 5
-    if: false  # disable this job -- ROS2 needs to be updated to support ISDevice & DeviceManager
-
-    container:
-      image: osrf/ros:jazzy-desktop
-      options: --device-cgroup-rule="c 166:* rmw"
-      volumes:
-        - "/dev:/dev"
-
-    defaults:
-      run:
-        working-directory: ../ROS/ros2_ws # This is outside the scope of git
-        shell: bash
-
-    steps:
-      - name: Update Git & CMake versions
-        working-directory: .
-        run: |
-          echo "::group::Install software-properties-common and dependencies."
-          apt-get update && apt -y install software-properties-common dirmngr apt-transport-https lsb-release ca-certificates libyaml-cpp-dev gpg wget curl
-          echo "::endgroup::"
-          echo "::group::Configure git-core PPA and install latest."
-          add-apt-repository ppa:git-core/ppa -y && apt -y install git
-          echo "::endgroup::"
-          git --version
-          echo "::group::Configure Kitware CMake PPA and install latest."
-          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
-          echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ `lsb_release -sc` main" | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
-          apt-get update
-          test -f /usr/share/doc/kitware-archive-keyring/copyright ||
-          rm /usr/share/keyrings/kitware-archive-keyring.gpg  
-          apt-get -y install kitware-archive-keyring cmake
-          echo "::endgroup::"
-          cmake --version
-
-      - name: Install libboost and other pre-checkout dependencies
-        run: |
-          /ros_entrypoint.sh /bin/bash -e -c "
-          mkdir -p .cache/pip
-          apt-get update && apt-get -y install libboost-all-dev python3-pip python3-venv python3-git python3-semver
-          rm -rf ../../inertial-sense-sdk/* log/ build/ install/ &>/dev/null || true 
-          "
-
-      - name: Checkout source and submodules
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
-          fetch-depth: 0  # Fetches full commit history, needed for repo info steps in build
-
-      - name: Install dependencies
-        working-directory: scripts
-        run: |
-          /ros_entrypoint.sh /bin/bash -e -c "
-          cd ../../inertial-sense-sdk/scripts
-          ./install_sdk_dependencies.sh
-          ./install_python_dependencies.sh
-          ./install_gtest.sh
-          chown -R 1003:1003 ../../
-          "
-
-      # - name: Install dependencies
+      # - name: Build LogInspector
       #   run: |
-      #     /ros_entrypoint.sh /bin/bash -e -c "
-      #     ../../inertial-sense-sdk/scripts/install_python_dependencies.sh
-      #     "
+      #     ./install_log_inspector_dependencies.sh
+      #     ./build_log_inspector.sh
 
-      - name: Build IS SDK library
-        run: |
-          /ros_entrypoint.sh /bin/bash -e -c "
-          git config --global --add safe.directory /__w/inertial-sense-sdk/inertial-sense-sdk
-          ../../inertial-sense-sdk/scripts/build_is_sdk.sh
-          "
+      # - name: Build SDK Examples
+      #   run: python3 build_manager.py SDK_Examples ../ExampleProjects
 
-      - name: Build ROS2 bridge
-        run: |
-          /ros_entrypoint.sh /bin/bash -e -c "
-          # find . -name "libInertialSenseSDK*" -delete
-          # rm log/ build/ install/ src/inertial-sense-sdk/CMakeCache.txt &>/dev/null || true
-          git config --global --add safe.directory /__w/inertial-sense-sdk/inertial-sense-sdk
-          colcon build
-          "
+  # ba_windows:
+  #   name: "General Software Windows"
+  #   runs-on: [self-hosted, windows, x64]
+  #   # if: false  # disable this job
+  #   # if: (github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/develop')   # Only run job on these branches
 
-      - name: Run Functional/Integration Tests (via hardware)
-        run: |
-          /ros_entrypoint.sh /bin/bash -e -c "          
-          source install/setup.bash
-          ros2 run inertial_sense_ros2 test_inertial_sense_ros2
-          "
+  #   defaults:
+  #     run:
+  #       working-directory: scripts/windows
 
-      - name: Cleanup build folder to prevent future errors (maybe remove?)
-        run: |
-          rm -rf ./* || true
-          rm -rf ./.??* || true
+  #   steps:
+  #     - name: Git checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         # token: ${{ secrets.ALL_REPO_PAT }}
+  #         submodules: recursive
+  #         fetch-depth: 0  # Fetches full commit history, needed for repo info steps in build
+
+  #     - name: Install dependencies
+  #       run: ./install_sdk_dependencies.bat
+
+  #     - name: Clean all
+  #       run: ./clean_all.bat
+
+  #     - name: Build IS SDK library
+  #       run: ./build_is_sdk.bat
+
+  #     - name: Build Unit Tests
+  #       run: ./build_unit_tests.bat
+
+  #     - name: Run Unit Tests
+  #       run: ./build_unit_tests.bat --no-build --test
+        
+  #     - name: Build CLTool
+  #       run: ./build_cltool.bat
+
+  #     - name: Build LogInspector
+  #       run: ./build_log_inspector.bat
+
+  #     - name: Build SDK Examples
+  #       run: ./build_sdk_examples.bat
+
+  # ros1-bridge-tests:
+  #   name: "ROS1 Bridge Tests"
+  #   runs-on: [self-hosted, Linux, X64, docker, focal]
+  #   timeout-minutes: 5
+  #   if: false  # disable this job -- ROS1 has been EOL'd and will be phased out.  We can no longer support it.
+
+  #   env:
+  #     ROS_CI_DESKTOP: "`lsb_release -cs`"  # e.g. [trusty|xenial|...]
+  #     ROS_DISTRO: noetic
+
+  #   container:
+  #     image: ros:noetic
+  #     #options: --privileged -v /dev:/dev
+  #     options: --device-cgroup-rule="c 166:* rmw"
+  #     volumes:
+  #       - "/dev:/dev"
+
+  #   defaults:
+  #     run:
+  #       working-directory: ../ROS/catkin_ws
+  #       shell: bash
+
+  #   steps:
+  #     - name: Update Git & CMake versions
+  #       working-directory: .
+  #       run: |
+  #         echo "::group::Install software-properties-common and dependencies."
+  #         apt-get update && apt -y install software-properties-common dirmngr apt-transport-https lsb-release ca-certificates libyaml-cpp-dev gpg wget curl
+  #         echo "::endgroup::"
+  #         echo "::group::Configure git-core PPA and install latest."
+  #         add-apt-repository ppa:git-core/ppa -y && apt -y install git
+  #         echo "::endgroup::"
+  #         git --version
+  #         echo "::group::Configure Kitware CMake PPA and install latest."
+  #         wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
+  #         echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ `lsb_release -sc` main" | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
+  #         apt-get update
+  #         test -f /usr/share/doc/kitware-archive-keyring/copyright ||
+  #         rm /usr/share/keyrings/kitware-archive-keyring.gpg  
+  #         apt-get -y install kitware-archive-keyring cmake
+  #         echo "::endgroup::"
+  #         cmake --version
+
+  #     - name: Checkout source and submodules
+  #       uses: actions/checkout@v4
+  #       with:
+  #         # token: ${{ secrets.ALL_REPO_PAT }}
+  #         fetch-depth: 0  # Fetches full commit history, needed for repo info steps in build
+  #         submodules: recursive
+
+  #     - name: Install dependencies
+  #       working-directory: scripts
+  #       run: |
+  #         apt-get update && apt-get -y install python3-pip python3-venv python3-git python3-semver
+  #         ./install_sdk_dependencies.sh
+  #         ./install_python_dependencies.sh
+  #         ./install_gtest.sh
+
+  #     - name: Setup ROS environment
+  #       run: |
+  #         source /opt/ros/$ROS_DISTRO/setup.bash
+  #         echo "::group::Install ROS packages."
+  #         apt -y install ros-${ROS_DISTRO}-tf libusb-1.0-0-dev
+  #         echo "::endgroup::"
+  #         git config --global --add safe.directory /__w/inertial-sense-sdk/inertial-sense-sdk
+
+  #     - name: Setup Catkin Workspace and Build
+  #       run: |
+  #         source /opt/ros/$ROS_DISTRO/setup.bash
+  #         catkin_make -DCATKIN_BLACKLIST_PACKAGES="inertial_sense_ros2"
+  #         catkin_make test_unit_tests
+  #         catkin_make test_ros_bridge 
+
+  #     - name: Run Unit Tests
+  #       run: |          
+  #         source devel/setup.bash
+  #         rm -rf build/test_results
+  #         roscore &
+  #         catkin_make run_tests_inertial_sense_ros_gtest_test_unit_tests
+  #         catkin_test_results
+  #         pkill roscore
+
+  #     - name: Run Functional/Integration Tests (via hardware)
+  #       run: |
+  #         source devel/setup.bash
+  #         roscore &
+  #         catkin_make run_tests_inertial_sense_ros_gtest_test_ros_bridge
+  #         catkin_test_results
+
+  #     - name: Cleanup build folder to prevent future errors (Remove maybe?)
+  #       run: |
+  #         rm -rf ./* || true
+  #         rm -rf ./.??* || true
+
+  # ros2-bridge-tests:
+  #   name: "ROS2 Bridge Tests"
+  #   runs-on: [self-hosted, Linux, X64, docker, focal]
+  #   timeout-minutes: 5
+  #   if: false  # disable this job -- ROS2 needs to be updated to support ISDevice & DeviceManager
+
+  #   container:
+  #     image: osrf/ros:jazzy-desktop
+  #     options: --device-cgroup-rule="c 166:* rmw"
+  #     volumes:
+  #       - "/dev:/dev"
+
+  #   defaults:
+  #     run:
+  #       working-directory: ../ROS/ros2_ws # This is outside the scope of git
+  #       shell: bash
+
+  #   steps:
+  #     - name: Update Git & CMake versions
+  #       working-directory: .
+  #       run: |
+  #         echo "::group::Install software-properties-common and dependencies."
+  #         apt-get update && apt -y install software-properties-common dirmngr apt-transport-https lsb-release ca-certificates libyaml-cpp-dev gpg wget curl
+  #         echo "::endgroup::"
+  #         echo "::group::Configure git-core PPA and install latest."
+  #         add-apt-repository ppa:git-core/ppa -y && apt -y install git
+  #         echo "::endgroup::"
+  #         git --version
+  #         echo "::group::Configure Kitware CMake PPA and install latest."
+  #         wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
+  #         echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ `lsb_release -sc` main" | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
+  #         apt-get update
+  #         test -f /usr/share/doc/kitware-archive-keyring/copyright ||
+  #         rm /usr/share/keyrings/kitware-archive-keyring.gpg  
+  #         apt-get -y install kitware-archive-keyring cmake
+  #         echo "::endgroup::"
+  #         cmake --version
+
+  #     - name: Install libboost and other pre-checkout dependencies
+  #       run: |
+  #         /ros_entrypoint.sh /bin/bash -e -c "
+  #         mkdir -p .cache/pip
+  #         apt-get update && apt-get -y install libboost-all-dev python3-pip python3-venv python3-git python3-semver
+  #         rm -rf ../../inertial-sense-sdk/* log/ build/ install/ &>/dev/null || true 
+  #         "
+
+  #     - name: Checkout source and submodules
+  #       uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #         fetch-depth: 0  # Fetches full commit history, needed for repo info steps in build
+
+  #     - name: Install dependencies
+  #       working-directory: scripts
+  #       run: |
+  #         /ros_entrypoint.sh /bin/bash -e -c "
+  #         cd ../../inertial-sense-sdk/scripts
+  #         ./install_sdk_dependencies.sh
+  #         ./install_python_dependencies.sh
+  #         ./install_gtest.sh
+  #         chown -R 1003:1003 ../../
+  #         "
+
+  #     # - name: Install dependencies
+  #     #   run: |
+  #     #     /ros_entrypoint.sh /bin/bash -e -c "
+  #     #     ../../inertial-sense-sdk/scripts/install_python_dependencies.sh
+  #     #     "
+
+  #     - name: Build IS SDK library
+  #       run: |
+  #         /ros_entrypoint.sh /bin/bash -e -c "
+  #         git config --global --add safe.directory /__w/inertial-sense-sdk/inertial-sense-sdk
+  #         ../../inertial-sense-sdk/scripts/build_is_sdk.sh
+  #         "
+
+  #     - name: Build ROS2 bridge
+  #       run: |
+  #         /ros_entrypoint.sh /bin/bash -e -c "
+  #         # find . -name "libInertialSenseSDK*" -delete
+  #         # rm log/ build/ install/ src/inertial-sense-sdk/CMakeCache.txt &>/dev/null || true
+  #         git config --global --add safe.directory /__w/inertial-sense-sdk/inertial-sense-sdk
+  #         colcon build
+  #         "
+
+  #     - name: Run Functional/Integration Tests (via hardware)
+  #       run: |
+  #         /ros_entrypoint.sh /bin/bash -e -c "          
+  #         source install/setup.bash
+  #         ros2 run inertial_sense_ros2 test_inertial_sense_ros2
+  #         "
+
+  #     - name: Cleanup build folder to prevent future errors (maybe remove?)
+  #       run: |
+  #         rm -rf ./* || true
+  #         rm -rf ./.??* || true
